# Generated by Django 3.2 on 2021-05-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='patient',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
