# Generated by Django 3.1.7 on 2021-03-24 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210324_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('background_type', models.CharField(choices=[('INH', 'Inherited'), ('PAT', 'Pathologic'), ('ANG', 'Andrological and Gyneco-obstetric'), ('NOP', 'No pathologic')], max_length=50)),
                ('background_subtype', models.CharField(choices=[('INF', 'Infectious contagious'), ('CHR', 'Chronic degenerative'), ('TRAU', 'Traumatological'), ('ALL', 'Allergy'), ('SUR', 'Surgical'), ('HOS', 'Hospitalization'), ('TRAN', 'Transfusion'), ('ADD', 'Addiction'), ('GEN', 'General'), ('AND', 'Andrological'), ('GYN', 'Gyneco-obstetric'), ('PLA', 'Living place'), ('HYG', 'Hygiene'), ('DIE', 'Diet'), ('ZOO', 'Zoonosis')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PacientMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
