# Generated by Django 3.1.7 on 2021-03-24 20:21

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210324_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.utils.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedicSpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicmore')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specialty')),
            ],
        ),
        migrations.AddField(
            model_name='medicmore',
            name='specialties',
            field=models.ManyToManyField(related_name='medics', through='core.MedicSpecialty', to='core.Specialty'),
        ),
    ]
