# Generated by Django 3.1.7 on 2021-03-24 20:45

import core.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210324_2021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PacientMore',
            new_name='PatientMore',
        ),
        migrations.DeleteModel(
            name='Pacient',
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PAC', 'Patient'), ('MED', 'Medic')], max_length=50), default=core.models.set_default_user_type, size=None),
        ),
    ]
