# Generated by Django 3.1.7 on 2021-03-25 20:46

import core.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210324_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PAT', 'Patient'), ('MED', 'Medic')], max_length=50), default=core.models.set_default_user_type, size=None),
        ),
    ]
