# Generated by Django 3.1.7 on 2021-03-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210325_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='core.patient'),
        ),
    ]
