# Generated by Django 3.1.7 on 2021-04-01 18:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210330_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmore',
            name='allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='patientmore',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
