# Generated by Django 3.1.7 on 2021-04-01 19:57

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('U', 'Undefined')], default=core.utils.set_default_sext_type, max_length=10),
        ),
    ]
