# Generated by Django 3.1.7 on 2021-04-01 23:45

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('U', 'Not Specified')], default=core.utils.set_default_sex_type, max_length=10),
        ),
    ]
