# Generated by Django 3.2 on 2021-04-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210401_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='date_of_diagnosis',
            field=models.DateField(),
        ),
    ]
