# Generated by Django 3.2 on 2021-04-29 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmore',
            old_name='alergies',
            new_name='allergies',
        ),
    ]
