# Generated by Django 3.2 on 2021-04-29 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_alergies_patientmore_allergies'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medics', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='patient_medic',
            field=models.ManyToManyField(through='core.PatientMedic', to=settings.AUTH_USER_MODEL),
        ),
    ]
