# Generated by Django 3.2 on 2021-05-03 19:36

from django.db import migrations, models
import django.db.models.deletion

def remove_patient_medic_relations(apps, schema_editor):
    PatientMedic = apps.get_model('core', 'PatientMedic')
    PatientMedic.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210430_0011'),
    ]

    operations = [
        migrations.RunPython(remove_patient_medic_relations),
        migrations.RemoveField(
            model_name='user',
            name='medics',
        ),
        migrations.AddField(
            model_name='patientmore',
            name='medics',
            field=models.ManyToManyField(related_name='patients', through='core.PatientMedic', to='core.MedicMore'),
        ),
        migrations.AlterField(
            model_name='patientmedic',
            name='medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicmore'),
        ),
        migrations.AlterField(
            model_name='patientmedic',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patientmore'),
        ),
    ]
